name: i_player
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  video_player: ^2.8.6
  wakelock_plus: ^1.2.5
  font_awesome_flutter: ^10.7.0
  screen_brightness: ^1.0.1
  dio: ^5.4.3+1
  screen_protector: ^1.4.2
  flutter_windowmanager: ^0.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      android:
        package: uz.akramjon.i_player
        pluginClass: IPlayerPlugin
      ios:
        pluginClass: IPlayerPlugin
      linux:
        pluginClass: IPlayerPlugin
      macos:
        pluginClass: IPlayerPlugin
      windows:
        pluginClass: IPlayerPluginCApi
      web:
        pluginClass: IPlayerWeb
        fileName: i_player_web.dart